SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

WINDOW_TITLE = "Frogger"

BG_COLOR = "#060C17"

TILE_WIDTH = 80
TILE_HEIGHT = 80
TILE_OUTLINE_COLOR = "#FFFFFF"

GRID_HEIGHT_COUNT = int(SCREEN_WIDTH / TILE_WIDTH)
GRID_WIDTH_COUNT = int(SCREEN_HEIGHT / TILE_HEIGHT)

PLAYER_WIDTH = 60
PLAYER_HEIGHT = 60
PLAYER_COLOR = "#C4F7FF"
