from math import pi

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

WINDOW_TITLE = "Pong"

BG_COLOR = "#060C17"

PLAYER_COLOR = "#C4F7FF"
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 128

BALL_COLOR = "#afe4ff"
BALL_RADIUS = 8
MAX_BOUNCE_ANGLE = 5 * pi / 12

FONT = "didot.ttf"
FONT_SIZE = 72
FONT_COLOR = "#C4F7FF"

SCORE_1_POS = ((SCREEN_WIDTH / 2) - (SCREEN_WIDTH / 12), 30)
SCORE_2_POS = ((SCREEN_WIDTH / 2) + (SCREEN_WIDTH / 11), 30)
